service: serverless1

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
#  memorySize: 128
  iam:
    role: arn:aws:iam::522856531149:role/serverless1-dev-us-east-1-lambdaRole
  environment:
    NLTK: /var/task/nltk_data
plugins:
 - serverless-wsgi
 - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false

# configValidationMode: off

package:
  patterns:
    - '!nltk/**'
    - '!node_modules/**'
    # - '!.vscode/**'
    # - '!.serverless/**'
    # - '!_pycache_/**'
    # - '!.gitignore/**'
    # - '!README.md/**'
    # - '!data.json/**'
    - '!venv/**'

functions:
  app:
    handler: wsgi.handler
    # handler: handler.app
  # extract:
  #   handler: handler.extract
    # url: true
    url:
      # Configure CORS in details:
      authType: NONE
      cors:
        # allowCredentials: …
        # allowedHeaders: …
        # allowedMethods: …
        allowedOrigins: "*"
        # exposedResponseHeaders: …
        maxAge: 86400
    timeout: 900
    memorySize: 4096
    runtime: python3.8
    ephemeralStorageSize: 512
    events:
     - http: ANY /
     - http: 'ANY /{proxy+}'
    #  - cors: true
    # layers:
    #   - {Ref: NltkLambdaLayer}
